// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zygcxcsrsouqufinknnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Z2N4Y3Nyc291cXVmaW5rbm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODk1NTQsImV4cCI6MjA2MjI2NTU1NH0.ec8Rukehg8NZ__br4hTYoEPorRckqqYW9BINkBhivNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);